name: Build APKs (SOMA Offline Demo)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Grant Gradle permissions
        run: chmod +x ./gradlew

      - name: Clean
        run: ./gradlew clean

      - name: Build Consumer
        run: ./gradlew :consumer-app:assembleDebug --stacktrace

      - name: Build Merchant
        run: ./gradlew :merchant-app:assembleDebug --stacktrace

      - name: Upload Consumer APK
        uses: actions/upload-artifact@v4
        with:
          name: consumer-debug-apk
          path: consumer-app/build/outputs/apk/debug/*.apk

      - name: Upload Merchant APK
        uses: actions/upload-artifact@v4
        with:
          name: merchant-debug-apk
          path: merchant-app/build/outputs/apk/debug/*.apk
