name: Build APKs (SOMA Offline Demo)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses

      - name: Install Build Tools & Platforms
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Gradle Build (no wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: |
            :merchant-app:assembleDebug
            :consumer-app:assembleDebug

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: soma-apks
          path: |
            merchant-app/build/outputs/apk/debug/*.apk
            consumer-app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
